import { NgModule } from '@angular/core';

import {
  MdButtonModule,
  MdCheckboxModule,
  MdDialogModule,
  MdIconModule,
  MdInputModule,
  MdOptionModule,
  MdRippleModule,
  MdSelectModule,
} from '@angular/material'

@NgModule({
  imports: [
    // MdAutocompleteModule,
    // MdCardModule,
    // MdChipsModule,
    // MdCoreModule,
    // MdLineModule,
    // MdListModule,
    // MdMenuModule,
    MdOptionModule,
    // MdRadioModule,
    // MdSelectionModule,
    MdSelectModule,
    MdIconModule,
    MdDialogModule,
    MdInputModule,
    MdCheckboxModule,
    MdRippleModule,
    MdButtonModule,
    // MdSidenavModule,
    // MdSliderModule,
    // MdTabsModule,
    // MdToolbarModule,
    // MdTooltipModule,
    // MdButtonToggleModule,
    // MdGridListModule,
    // MdProgressBarModule,
    // MdProgressSpinnerModule,
    // MdSlideToggleModule,
    // MdSnackBarModule,
  ],
  exports: [
    // MdAutocompleteModule,
    // MdCardModule,
    // MdChipsModule,
    // MdCoreModule,
    // MdLineModule,
    // MdListModule,
    // MdMenuModule,
    MdOptionModule,
    // MdRadioModule,
    // MdSelectionModule,
    MdSelectModule,
    MdIconModule,
    MdDialogModule,
    MdInputModule,
    MdCheckboxModule,
    MdRippleModule,
    MdButtonModule,
    // MdSidenavModule,
    // MdSliderModule,
    // MdTabsModule,
    // MdToolbarModule,
    // MdTooltipModule,
    // MdButtonToggleModule,
    // MdGridListModule,
    // MdProgressBarModule,
    // MdProgressSpinnerModule,
    // MdSlideToggleModule,
    // MdSnackBarModule,
  ],
})
export class CustomMaterialModule { }
