import { NgModule } from '@angular/core';

import {
  MatButtonModule,
  MatCheckboxModule,
  MatDialogModule,
  MatIconModule,
  MatInputModule,
  MatOptionModule,
  MatRippleModule,
  MatSelectModule,
  MatStepperModule
} from '@angular/material';

@NgModule({
  imports: [
    MatOptionModule,
    MatSelectModule,
    MatIconModule,
    MatDialogModule,
    MatInputModule,
    MatCheckboxModule,
    MatRippleModule,
    MatButtonModule,
    MatStepperModule,
    // MatAutocompleteModule,
    // MatCardModule,
    // MatChipsModule,
    // MatCoreModule,
    // MatLineModule,
    // MatListModule,
    // MatMenuModule,
    // MatRadioModule,
    // MatSelectionModule,
    // MatSidenavModule,
    // MatSliderModule,
    // MatTabsModule,
    // MatToolbarModule,
    // MatTooltipModule,
    // MatButtonToggleModule,
    // MatGridListModule,
    // MatProgressBarModule,
    // MatProgressSpinnerModule,
    // MatSlideToggleModule,
    // MatSnackBarModule,
  ],
  exports: [
    MatOptionModule,
    MatSelectModule,
    MatIconModule,
    MatDialogModule,
    MatInputModule,
    MatCheckboxModule,
    MatRippleModule,
    MatButtonModule,
    MatStepperModule,
    // MatAutocompleteModule,
    // MatCardModule,
    // MatChipsModule,
    // MatCoreModule,
    // MatLineModule,
    // MatListModule,
    // MatMenuModule,
    // MatRadioModule,
    // MatSelectionModule,
    // MatSidenavModule,
    // MatSliderModule,
    // MatTabsModule,
    // MatToolbarModule,
    // MatTooltipModule,
    // MatButtonToggleModule,
    // MatGridListModule,
    // MatProgressBarModule,
    // MatProgressSpinnerModule,
    // MatSlideToggleModule,
    // MatSnackBarModule,
  ],
})
export class CustomMaterialModule { }
